### ISSUE TITLE
Mode of LP3

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/fda-statistics#16]
We need to implement the mode of LP3/ cut out the not implemented exception

**Comment by HenryGeorgist** [comment]
is mode ever used for production code?

if not, we should drop it from idistribution

**Comment by rnugent3** [comment]
Yes - triangular distributions

**Comment by HenryGeorgist** [comment]
good point.

**Comment by HenryGeorgist** [comment]
i think stored attribute is what we really need - it doesnt have to be a parameter of idistribution to be a storedattribute.

**Comment by rnugent3** [comment]
how do we access the attribute value? for example in a test class, we have: 

`
IDistribution d = new Triangular(min, mostlikely,max ,n);
Assert.Equal(d.Mode.....
`

**Comment by HenryGeorgist** [comment]
not sure exactly where that is in our tests, but it is essentially a test that a constructor and property access works. that is not the business logic of a distribution, that test should be reconsidered for its value in our codebase.

but the point remains, how do we get to the fields we need. 

We have IDistribution to make all distributions homogenious in their use. We use them for only a few things that i know of.
The Inverse CDF. 
FIT(IData)

We have an extension method for Bootstrap, so that is the only other "distribution level" activity i am aware of

We also have validation which should be the responsibility of a segregated interface for IValidate

Everything else is access and storage. which should be segregated interfaces (ISeralizeToXML) for instance.

our tests and access should be thought of within the context of what our program is supposed to do. 

The StoredAttribute can be used to signal in the viewmodel what properties on the class should be used for visualization. we use reflection for that.

**Comment by rnugent3** [comment]
Thanks, Will. This is in the serialization tests. 

Having removed mode from IDistribution, could you please suggest a way to ask a triangular distribution for its mode?

**Comment by HenryGeorgist** [comment]
option 1. direct cast to a triangular distribution and ask for the mode
option 2. make the equals method on distributions actually make sense and compare the methods that define the distribution itself.
